### ISSUE TITLE
Milestone 2

### ISSUE THREAD

**Issue by ronadarabi** [ronadarabi/cse151a-project#1]
- [x] Create a GitHub ID
- [x] Create a GitHub Repository (Public or Private it is up to you. In the end it will have to be Public) and add your group members as collaborators
- [x] Perform the data exploration step (i.e. evaluate your data, # of observations, details about your data distributions, scales, missing data, column descriptions) Note: For image data you can still describe your data by the number of classes, # of images, plot example classes of the image, size of images, are sizes uniform? Do they need to be cropped? normalized? etc.
- [x] Plot your data. For tabular data, you will need to run scatters, for image data, you will need to plot your example classes.
- [x] How will you preprocess your data? You should explain this in your README.md file and link your Jupyter notebook to it. All code and  Jupyter notebooks have be uploaded to your repo.
- [x] You must also include in your Jupyter Notebook, a link for data download and environment setup requirements: 
 !wget !unzip like functions as well as !pip install functions for non standard libraries not available in colab are required to be in the top section of your jupyter lab notebook. Or having the data on GitHub (you will need the academic license for GitHub to do this, larger datasets will require a link to external storage).
