### ISSUE TITLE
Milestone 3

### ISSUE THREAD

**Issue by ronadarabi** [ronadarabi/cse151a-project#2]
- [x] Finish major preprocessing, this includes scaling and/or transforming your data, imputing your data, encoding your data, feature expansion, Feature expansion (example is taking features and generating new features by transforming via polynomial, log multiplication of features).
- [x] Train your first model
- [x] Evaluate your model and compare training vs. test error
- [x] Answer the questions: Where does your model fit in the fitting graph? and What are the next models you are thinking of and why?
- [x] Update your README.md to include your new work and updates you have all added. Make sure to upload all code and notebooks. Provide links in your README.md
- [x] Conclusion section: What is the conclusion of your 1st model? What can be done to possibly improve it?
- [x] Please make sure preprocessing is complete and your first model has been trained. If you are doing supervised learning include example ground truth and predictions for train, validation and test.
